github_checks:
  annotations: true

ignore:
  - "test_util/**"
  - ".github/benchmarks/**"

coverage:
  ignore:
    - "test_util/**"
    - ".github/benchmarks/**"
  status:
    patch:
      default:
        target: 80%
